apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-shard
  namespace: dev
spec:
  serviceName: "mongo-shard"
  replicas: 3
  selector:
    matchLabels:
      app: mongo-shard
  template:
    metadata:
      labels:
        app: mongo-shard
    spec:
      containers:
      - name: mongo
        image: mongo:7.0
        command:
          - mongod
          - "--shardsvr"            # ⬅️ MODE SHARD SERVER
          - "--replSet"
          - "rs-shard"              # ⬅️ REPLICA SET DIFFÉRENT
          - "--bind_ip_all"
          - "--port"
          - "27017"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-shard-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-shard-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-shard
  namespace: dev
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo-shard