apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-config
  namespace: dev
spec:
  serviceName: "mongo-config"
  replicas: 3
  selector:
    matchLabels:
      app: mongo-config
  template:
    metadata:
      labels:
        app: mongo-config
    spec:
      containers:
      - name: mongo
        image: mongo:7.0
        command:
          - mongod
          - "--configsvr"
          - "--replSet"
          - "rs-config"
          - "--bind_ip_all"
          - "--port"
          - "27017"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-config-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-config-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "hostpath"  # ou "standard" selon ton cluster
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-config
  namespace: dev
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo-config